[supervisord]
nodaemon=true
logfile=/dev/null

[program:Correspond]
command=/app/Correspond
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:LogonServer]
command=/app/LogonServer
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:GameServer]
command=/app/GameServer -s 1
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:ChatServer]
command=/app/ChatServer
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
